### ISSUE TITLE
"FileNotFoundError: [Errno 2] No such file or directory: './data/graphs/mimic3_dp.pkl'"

### ISSUE THREAD

**Issue by happywinder** [howardchanth/HGEHR#1]
Dear authors,when I run main.py ,it reports"FileNotFoundError: [Errno 2] No such file or directory: './data/graphs/mimic3_dp.pkl'",how can i get mimic3_dp.pkl,i can't find anywhere to construct this file,Could you upload this file ?

**Comment by howardchanth** [comment]
Hi thanks for your interest in our work. This file is the output of graph_constructor.py which is a dgl graph object. To construct the graph you need the processed mimic3_dataset object (by pyhealth). And to get this dataset you need the raw mimic3 data in tabular form. However, we cannot release this dataset due to privacy protocol and you can get it by completing a course on physionet.

**Comment by happywinder** [comment]
thanks!!!!
